version: "3.1"
services:
  rabbitmq:
    container_name: rabbitmq-poc
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"

  sender:
    container_name: rabbitmq-sender
    build:
      context: ./
      dockerfile: sender.Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq

  receiver:
    container_name: rabbitmq-receiver
    build:
      context: ./
      dockerfile: receiver.Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
